[log]
level = "debug"
destination = "stdout"
filename = "server.log"

[settings]
stopTimeout = "10s"
useLongPolling = true
serverHost = "localhost:8080"
webhookURL = "https://telegrambot.syodo.com.ua/syodo-bot"
longPullingTimeout = 4
requestTimeout = "10s"
testMode = true
orderTTL = "30m"

[app]
webAppURL = "https://telegrambot.syodo.com.ua/syodo"
syodoAPIURL = "https://hjrc5e9go8.execute-api.eu-central-1.amazonaws.com/dev"
