# Start cmd description
startDescription = "Start"
# Start cmd, contains buttons for site, instagram and facebook, data: Message
start = """
Hello <i>{{ .From.FirstName }}</i>
"""

# Help cmd description
helpDescription = "Help"
# Help cmd, data: Message
help = """
Help
"""

# Buttons text
siteButtonText = "syodo.com"
instagramButtonText = "Instagram"
facebookButtonText = "Facebook"

# URLs
siteURL = "https://syodo.com.ua"
instagramURL = "https://www.instagram.com/syodo.sushi"
facebookURL = "https://www.facebook.com/syodo.sushi.lviv"
