# Start cmd description
startDescription = "З чого почати?"
# Start cmd, contains buttons for site, instagram and facebook, data: Message
start = """
Привіт <i>{{ .From.FirstName }}</i> 👋

Я SYODŌ 🍱 бот, допоможу Вам замовити свої найсмачніші суші (та не тільки) прямо з Телеграму.

Допомога: /help

Скористайтеся кнопкю ▼ <u><b>Меню</b></u> ▼, щоб зробити замовлення.
"""

# Help cmd description
helpDescription = "Допомога"
# Help cmd, data: Message
help = """
Щоб зробити замовлення просто нажміть на кнопку ▼ <u><b>Меню</b></u> ▼, та почніть обирати ваше замовлення, після чого |
переконайтеся, що все введено вірно та продовжіть з оплатою прямо у Телеграм.

За допомогою Ви можете звертися за телефоном: +380677229345

Або за посиланнями ▼ нижче ▼
"""

# Buttons text
siteButtonText = "syodo.com.ua"
instagramButtonText = "Instagram"
facebookButtonText = "Facebook"

# URLs
siteURL = "https://syodo.com.ua"
instagramURL = "https://www.instagram.com/syodo.sushi"
facebookURL = "https://www.facebook.com/syodo.sushi.lviv"

# Menu button text
menuButton = "Меню"
# Web app URL
webAppURL = "https://mymm.gq/syodo"
