# Start cmd description
startDescription = "З чого почати?"
# Start cmd, contains buttons for site, instagram and facebook, data: Message
start = """
Привіт <i>{{ .From.FirstName }}</i> 👋

Я SYODŌ 🍱 бот, допоможу Вам замовити свої найсмачніші суші (та не тільки) прямо з Телеграму.

Допомога: /help

Скористайтеся кнопкю ▼ <u><b>Меню</b></u> ▼, щоб зробити замовлення.
"""

# Help cmd description
helpDescription = "Допомога"
# Help cmd, data: Message
help = """
Щоб зробити замовлення просто нажміть на кнопку ▼ <u><b>Меню</b></u> ▼, та почніть обирати ваше замовлення, після чого |
переконайтеся, що все введено вірно та продовжіть з оплатою прямо у Телеграм.

За допомогою Ви можете звертися за телефоном: +380677229345

Або за посиланнями ▼ нижче ▼
"""

# Buttons text
siteButtonText = "syodo.com.ua"
instagramButtonText = "Instagram"
facebookButtonText = "Facebook"

# URLs
siteURL = "https://syodo.com.ua"
instagramURL = "https://www.instagram.com/syodo.sushi"
facebookURL = "https://www.facebook.com/syodo.sushi.lviv"

# Menu button text
menuButton = "Меню"

# Error that is displayed if order was not found
orderNotFoundError = "На жаль, ми не можемо знайти Ваше замовлення"

# Error that is displayed if order was done with unexpected or empty delivery method
orderDeliveryError = "На жаль, ми не занємо як доставити Ваше замовлення"

# Error that is displayed if order was failed to checkout
orderCheckoutError = "На жаль, ми не змогли оформити Ваше замовлення"

# Error that is displayed if order is missing some info
orderInfoError = "На жаль, ми не змогли отримати всю інформацію про Ваше замовлення"

# Description of the order
orderDescription = "SYODŌ – доставка японської кухні, що поважає деталі!"

# Error that is displayed if calculating shipping price failed
calculateShippingPriceError = "На жаль, ми не змогли звизначити деталей доставки Вашого замовлення"

# Success payment message, data: OrderDerails
successPayment = """
Дякуємо за оплату!
Замовлення #{{ .OrderID }}

Сума: {{ toPrice  .TotalAmount }}грн
Переглянути замовлення: {{ .OrderURL }}
"""

# Error that is displayed if order was not found after success payment
successPaymentOrderNotFoundError = """
На жаль, ми не можемо знайти Ваше замовлення

Звяжіться з адміністрацією за контактами зазначиними тут /help
"""
